name: tagger
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  tagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create tag
        id: tag
        run: |
          VERSION_FILE=".version"
          VERSION_VALUE=$(cat $VERSION_FILE)
          MAX_BRANCH_LENGTH=40
          FIXED_BRANCH=$(echo ${GITHUB_REF:11:${MAX_BRANCH_LENGTH}} | sed 's/[^[:alnum:]]/-/g')
          NEW_TAG=$(echo "$VERSION_VALUE-${FIXED_BRANCH}.$(date +%Y%m%d-%H%M%S)")
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
